apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: mydaemon
    namespace: aws
spec:
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: abc
      labels:
        app: myweb
    spec:
      containers:
        - name: ashish
          image: nginx
