apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: mywebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      name: mypod
      labels:
        app: mywebsite
    spec:
      containers:
        - name: mycontainer
          image: mysql
          envFrom:
            - secretRef:
                name: app-db

