apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-newdp
  labels:
    app: newdp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: newdp
  template:
    metadata:
      labels:
        app: newdp
    spec:
      containers:
        - name: shubham
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: privatesvc
spec:
  selector:
    app: newdp
  ports:
    - targetPort: 80
      port: 80
