apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ashish
        image: nginx
        ports:
          - containerPort: 80
      tolerations:
      - key: "machine"
        operator: "Equal"
        value: lowspec
        effect: "NoSchedule"
